[build]
  publish = "public"
  command = "hugo"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.46"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true" 

[context.production.environment]
  HUGO_VERSION = "0.46"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
